### ISSUE TITLE
Shared package.json does not reflect individual dependencies

### ISSUE THREAD

**Issue by gaearon** [voronianski/flux-comparison#62]
Currently each project has its own `package.json`, but really all dependencies are in the top-level `package.json`. Is this by design? Do you plan to change this?

**Comment by voronianski** [comment]
@gaearon this project started as comparison of 3 frameworks so shared `package.json` worked well at that point, but as for now I think it will be smarter to move dependencies inside folders' `package.json`s.

**Comment by gaearon** [comment]
Do you want to do this all at once, or are you fine with updating them one by one?
I can send a PR for Redux deps.

**Comment by voronianski** [comment]
@gaearon let's try one by one, thanks!

**Comment by gaearon** [comment]
#63

**Comment by voronianski** [comment]
https://github.com/voronianski/flux-comparison/commit/a62a97ae84634ca4e7c2677fa07e4cf9dc53125f

**Comment by voronianski** [comment]
I've left `react` in root folder's `package.json` (as well as some libs that are used almost everywhere e.g. `object-assign`, `es5-shim`, etc.) because components from `./common` folder also need React in them. 

As for me this looks fine, except that some libraries like Reflux or Fluxible have `react` as peerDependency and `npm install`s it inside of the solution folder. 

/cc @gaearon

**Comment by gaearon** [comment]
Awesome! Yes, shared `react` is sensible.
